# Generated by Django 5.1.4 on 2025-02-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_options_remove_payment_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Dispute',
        ),
    ]
