web: gunicorn --workers=3 --threads=3 --timeout=120 --log-level=debug bhara.wsgi:application
worker: celery -A bhara worker -l info
beat: celery -A bhara beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler