# Generated by Django 5.1.4 on 2025-04-21 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='advertisements.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='advertisements.product'),
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='advertisements.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='advertiseme_status_3ed8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='advertiseme_categor_3c4e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['location'], name='advertiseme_locatio_23427e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='advertiseme_created_a42d99_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['average_rating'], name='advertiseme_average_c27816_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.UniqueConstraint(fields=('product', 'duration_unit'), name='unique_duration_unit_per_product'),
        ),
        migrations.AddConstraint(
            model_name='unavailabledate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_range', False), models.Q(('is_range', True), ('range_start__isnull', False), ('range_end__isnull', False), ('range_end__gte', models.F('range_start'))), _connector='OR')), name='valid_date_range'),
        ),
    ]
