# Generated by Django 5.1.4 on 2025-04-21 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='advertisements.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='advertisements.product'),
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='advertisements.product'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.UniqueConstraint(fields=('product', 'duration_unit'), name='unique_duration_unit_per_product'),
        ),
        migrations.AddConstraint(
            model_name='unavailabledate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_range', False), models.Q(('is_range', True), ('range_start__isnull', False), ('range_end__isnull', False), ('range_end__gte', models.F('range_start'))), _connector='OR')), name='valid_date_range'),
        ),
    ]
