# Generated by Django 5.1.4 on 2025-04-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('photography_videography', 'Photography & Videography'), ('sports_outdoor', 'Sports & Outdoor'), ('camping_hiking', 'Camping & Hiking'), ('travel_luggage', 'Travel & Luggage'), ('event_party', 'Event & Party'), ('fashion_accessories', 'Fashion & Accessories'), ('electronics', 'Electronics'), ('tools_equipment', 'Tools & Equipment'), ('musical_instruments', 'Musical Instruments'), ('other', 'Other')], help_text='Product category', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('camera', 'photography_videography'), ('lens', 'photography_videography'), ('gimbal', 'photography_videography'), ('tripod', 'photography_videography'), ('drone', 'photography_videography'), ('lighting', 'photography_videography'), ('video_camera', 'photography_videography'), ('microphone', 'photography_videography'), ('stabilizer', 'photography_videography'), ('slider', 'photography_videography'), ('reflector', 'photography_videography'), ('monitor', 'photography_videography'), ('memory_card', 'photography_videography'), ('battery', 'photography_videography'), ('charger', 'photography_videography'), ('light_stand', 'photography_videography'), ('softbox', 'photography_videography'), ('backdrop', 'photography_videography'), ('cricket_bat', 'sports_outdoor'), ('football', 'sports_outdoor'), ('badminton_racket', 'sports_outdoor'), ('helmet', 'sports_outdoor'), ('sports_gear', 'sports_outdoor'), ('running_shoes', 'sports_outdoor'), ('bicycle', 'sports_outdoor'), ('skipping_rope', 'sports_outdoor'), ('backpack', 'camping_hiking'), ('headlamp', 'camping_hiking'), ('gas_can', 'camping_hiking'), ('raincover', 'camping_hiking'), ('poncho', 'camping_hiking'), ('jacket', 'camping_hiking'), ('sleeping_bag', 'camping_hiking'), ('tent', 'camping_hiking'), ('stove', 'camping_hiking'), ('water_bottle', 'camping_hiking'), ('hiking_pole', 'camping_hiking'), ('camping_chair', 'camping_hiking'), ('suitcase', 'travel_luggage'), ('travel_adapter', 'travel_luggage'), ('power_bank', 'travel_luggage'), ('travel_bag', 'travel_luggage'), ('trolley', 'travel_luggage'), ('sound_system', 'event_party'), ('decorations', 'event_party'), ('chair', 'event_party'), ('table', 'event_party'), ('stage_light', 'event_party'), ('projector', 'event_party'), ('tent', 'event_party'), ('formal_wear', 'fashion_accessories'), ('jewelry', 'fashion_accessories'), ('costume', 'fashion_accessories'), ('watch', 'fashion_accessories'), ('sunglasses', 'fashion_accessories'), ('laptop', 'electronics'), ('tablet', 'electronics'), ('smartphone', 'electronics'), ('projector', 'electronics'), ('speaker', 'electronics'), ('tv', 'electronics'), ('printer', 'electronics'), ('scanner', 'electronics'), ('router', 'electronics'), ('power_tools', 'tools_equipment'), ('hand_tools', 'tools_equipment'), ('measuring_tape', 'tools_equipment'), ('drill_machine', 'tools_equipment'), ('ladder', 'tools_equipment'), ('cleaning_equipment', 'tools_equipment'), ('guitar', 'musical_instruments'), ('keyboard', 'musical_instruments'), ('harmonium', 'musical_instruments'), ('tabla', 'musical_instruments'), ('microphone', 'musical_instruments'), ('amplifier', 'musical_instruments'), ('drum', 'musical_instruments'), ('violin', 'musical_instruments'), ('other', 'other')], help_text='Type of product (e.g., camera, lens)', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_year',
            field=models.CharField(help_text='Year product was purchased (YYYY)', max_length=4),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Product image file', max_length=255, upload_to='product_images/'),
        ),
    ]
