# Generated by Django 5.1.4 on 2025-01-22 18:27

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_product_average_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityperiod',
            options={'ordering': ['start_date'], 'verbose_name': 'Availability Period', 'verbose_name_plural': 'Availability Periods'},
        ),
        migrations.AddField(
            model_name='availabilityperiod',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this availability period'),
        ),
        migrations.AddField(
            model_name='pricingoption',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('maintenance', 'Under Maintenance'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('camera', 'Camera'), ('gimbal', 'Gimbal'), ('lighting', 'Lighting Equipment'), ('video_acc', 'Video Accessories'), ('microphone', 'Microphone'), ('studio_equip', 'Studio Equipment'), ('bicycle', 'Bicycle'), ('safety_gear', 'Helmets & Safety Gear'), ('cricket', 'Cricket Equipment'), ('football', 'Football & Soccer Equipment'), ('basketball', 'Basketball Equipment'), ('tennis', 'Tennis Equipment'), ('gym_equip', 'Gym Equipment'), ('tent', 'Tent'), ('sleeping_bag', 'Sleeping Bag'), ('camp_furniture', 'Camping Furniture'), ('hiking_gear', 'Hiking Gear'), ('camp_stove', 'Portable Stove'), ('cooler', 'Cooler'), ('speaker', 'Speaker'), ('dj_equip', 'DJ Equipment'), ('musical_inst', 'Musical Instruments'), ('karaoke', 'Karaoke Systems'), ('party_lights', 'Party Lights'), ('projector', 'Projector'), ('drone', 'Drone'), ('gaming', 'Gaming Console'), ('vr_equip', 'VR Equipment'), ('tablet', 'Tablet'), ('power_bank', 'Power Bank'), ('laptop', 'Laptop'), ('party_furniture', 'Tables & Chairs'), ('decorations', 'Decorations'), ('grill', 'Grills & BBQ Equipment'), ('bounce_house', 'Bounce House'), ('stage', 'Portable Stage'), ('power_tool', 'Power Tools'), ('hand_tool', 'Hand Tools'), ('garden_tool', 'Gardening Equipment'), ('pressure_washer', 'Pressure Washer'), ('ladder', 'Ladder'), ('paint_sprayer', 'Paint Sprayer')], db_index=True, help_text='Select the category that best describes your item', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Upload a product image (max 5MB)', upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='availabilityperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='advertiseme_start_d_5bcc07_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='advertiseme_categor_22284e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['location', 'category'], name='advertiseme_locatio_0db78d_idx'),
        ),
    ]
