# Generated by Django 5.1.4 on 2025-02-14 20:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0012_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a product image (max 5MB)', upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AlterModelOptions(
            name='availabilityperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'Availability Period', 'verbose_name_plural': 'Availability Periods'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_categor_c0ae5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_locatio_6804af_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_created_2d3a18_idx',
        ),
        migrations.RemoveField(
            model_name='pricingoption',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='pricingoption',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('camera', 'Camera'), ('gimbal', 'Gimbal'), ('lighting', 'Lighting Equipment'), ('video_acc', 'Video Accessories'), ('microphone', 'Microphone'), ('studio_equip', 'Studio Equipment'), ('bicycle', 'Bicycle'), ('safety_gear', 'Helmets & Safety Gear'), ('cricket', 'Cricket Equipment'), ('football', 'Football & Soccer Equipment'), ('basketball', 'Basketball Equipment'), ('tennis', 'Tennis Equipment'), ('gym_equip', 'Gym Equipment'), ('tent', 'Tent'), ('sleeping_bag', 'Sleeping Bag'), ('camp_furniture', 'Camping Furniture'), ('hiking_gear', 'Hiking Gear'), ('camp_stove', 'Portable Stove'), ('cooler', 'Cooler'), ('bag', 'Bag'), ('speaker', 'Speaker'), ('dj_equip', 'DJ Equipment'), ('musical_inst', 'Musical Instruments'), ('karaoke', 'Karaoke Systems'), ('party_lights', 'Party Lights'), ('projector', 'Projector'), ('drone', 'Drone'), ('power_bank', 'Power Bank'), ('laptop', 'Laptop'), ('party_furniture', 'Tables & Chairs'), ('decorations', 'Decorations'), ('grill', 'Grills & BBQ Equipment'), ('stage', 'Portable Stage'), ('power_tool', 'Power Tools'), ('hand_tool', 'Hand Tools'), ('garden_tool', 'Gardening Equipment'), ('ladder', 'Ladder'), ('paint_sprayer', 'Paint Sprayer')], db_index=True, help_text='Select the category that best describes your item', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_pricing', to='advertisements.pricingoption'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='advertiseme_categor_22284e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['location', 'owner'], name='advertiseme_locatio_71dc88_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='advertiseme_created_a42d99_idx'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisements.product'),
        ),
    ]
