# Generated by Django 5.1.4 on 2025-04-02 11:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0013_productimage_alter_availabilityperiod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityperiod',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_categor_22284e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_locatio_71dc88_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_created_a42d99_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('maintenance', 'Under Maintenance'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('camera', 'Camera'), ('gimbal', 'Gimbal'), ('lighting', 'Lighting Equipment'), ('video_acc', 'Video Accessories'), ('microphone', 'Microphone'), ('studio_equip', 'Studio Equipment'), ('bicycle', 'Bicycle'), ('safety_gear', 'Helmets & Safety Gear'), ('cricket', 'Cricket Equipment'), ('football', 'Football & Soccer Equipment'), ('basketball', 'Basketball Equipment'), ('tennis', 'Tennis Equipment'), ('gym_equip', 'Gym Equipment'), ('tent', 'Tent'), ('sleeping_bag', 'Sleeping Bag'), ('camp_furniture', 'Camping Furniture'), ('hiking_gear', 'Hiking Gear'), ('camp_stove', 'Portable Stove'), ('cooler', 'Cooler'), ('bag', 'Bag'), ('speaker', 'Speaker'), ('dj_equip', 'DJ Equipment'), ('musical_inst', 'Musical Instruments'), ('karaoke', 'Karaoke Systems'), ('party_lights', 'Party Lights'), ('projector', 'Projector'), ('drone', 'Drone'), ('power_bank', 'Power Bank'), ('laptop', 'Laptop'), ('party_furniture', 'Tables & Chairs'), ('decorations', 'Decorations'), ('grill', 'Grills & BBQ Equipment'), ('stage', 'Portable Stage'), ('power_tool', 'Power Tools'), ('hand_tool', 'Hand Tools'), ('garden_tool', 'Gardening Equipment'), ('ladder', 'Ladder'), ('paint_sprayer', 'Paint Sprayer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='advertiseme_categor_3c4e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['location'], name='advertiseme_locatio_23427e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='advertiseme_is_avai_6820b9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='advertiseme_status_3ed8c6_idx'),
        ),
        migrations.DeleteModel(
            name='AvailabilityPeriod',
        ),
    ]
