# Generated by Django 5.1.4 on 2025-04-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0016_make_fields_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
