# Generated by Django 5.1.4 on 2025-04-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0017_remove_product_images'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'order')},
        ),
    ]
