# Generated by Django 5.1.4 on 2025-04-03 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0019_alter_pricingtier_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list, help_text='List of image URLs for the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_tiers',
            field=models.JSONField(default=list, help_text='List of pricing tiers for different durations'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, help_text='Detailed description of the product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(default=1, help_text='Location where the product is available for pickup/delivery', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product has been rented'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unavailable_dates',
            field=models.JSONField(default=list, help_text='Dates when the product is not available for rental'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product has been viewed'),
        ),
        migrations.DeleteModel(
            name='PricingTier',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
