# Generated by Django 5.1.4 on 2025-04-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0020_alter_productimage_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='duration_unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_tiers',
            field=models.JSONField(default=list, help_text='List of pricing tiers, each containing duration_unit (day/week/month), max_period (maximum rental duration), and price (price per unit)'),
        ),
    ]
