# Generated by Django 5.1.4 on 2025-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0022_pricingtier_productimage_unavailabledate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_year',
            field=models.CharField(default='2025', help_text='Year of purchase (defaults to current year)', max_length=4),
        ),
    ]
