# Generated by Django 5.1.4 on 2025-04-04 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0023_alter_product_purchase_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='price',
            field=models.PositiveIntegerField(help_text='Price per duration unit in Taka', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
