# Generated by Django 5.1.4 on 2025-04-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0024_alter_pricingtier_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='price',
            field=models.PositiveIntegerField(help_text='Price per duration unit in Taka'),
        ),
    ]
