# Generated by Django 5.1.4 on 2025-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0025_alter_pricingtier_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('photography_videography', 'Photography & Videography'), ('sports_fitness', 'Sports & Fitness'), ('tools_equipment', 'Tools & Equipment'), ('electronics', 'Electronics'), ('musical_instruments', 'Musical Instruments'), ('party_events', 'Party & Events'), ('fashion_accessories', 'Fashion & Accessories'), ('home_garden', 'Home & Garden'), ('books_media', 'Books & Media'), ('toys_games', 'Toys & Games'), ('automotive', 'Automotive'), ('other', 'Other')], help_text='Product category', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('camera', 'photography_videography'), ('lens', 'photography_videography'), ('gimbal', 'photography_videography'), ('drone', 'photography_videography'), ('lighting', 'photography_videography'), ('tripod', 'photography_videography'), ('microphone', 'photography_videography'), ('video_camera', 'photography_videography'), ('bicycle', 'sports_fitness'), ('treadmill', 'sports_fitness'), ('yoga_mat', 'sports_fitness'), ('dumbbells', 'sports_fitness'), ('sports_equipment', 'sports_fitness'), ('power_tools', 'tools_equipment'), ('hand_tools', 'tools_equipment'), ('gardening_tools', 'tools_equipment'), ('cleaning_equipment', 'tools_equipment'), ('laptop', 'electronics'), ('tablet', 'electronics'), ('smartphone', 'electronics'), ('gaming_console', 'electronics'), ('tv', 'electronics'), ('speaker', 'electronics'), ('guitar', 'musical_instruments'), ('piano', 'musical_instruments'), ('drums', 'musical_instruments'), ('microphone', 'musical_instruments'), ('amplifier', 'musical_instruments'), ('tent', 'party_events'), ('table', 'party_events'), ('chair', 'party_events'), ('decorations', 'party_events'), ('sound_system', 'party_events'), ('formal_wear', 'fashion_accessories'), ('costume', 'fashion_accessories'), ('jewelry', 'fashion_accessories'), ('accessories', 'fashion_accessories'), ('furniture', 'home_garden'), ('kitchen_appliance', 'home_garden'), ('garden_tools', 'home_garden'), ('decor', 'home_garden'), ('book', 'books_media'), ('magazine', 'books_media'), ('movie', 'books_media'), ('game', 'books_media'), ('board_game', 'toys_games'), ('video_game', 'toys_games'), ('toy', 'toys_games'), ('puzzle', 'toys_games'), ('car', 'automotive'), ('bike', 'automotive'), ('scooter', 'automotive'), ('accessories', 'automotive'), ('other', 'other')], help_text='Product type', max_length=50),
        ),
    ]
