# Generated by Django 5.1.4 on 2025-01-23 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_remove_product_advertiseme_categor_22284e_idx_and_more'),
        ('rentals', '0002_escrowpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rental',
            name='rentals_ren_owner_i_a6dccf_idx',
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['owner', 'renter'], name='rentals_ren_owner_i_a25d25_idx'),
        ),
    ]
