# Generated by Django 5.1.4 on 2025-02-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_escrow_payment_alter_escrowpayment_payment_and_more'),
    ]

    operations = [
    ]
