# Generated by Django 5.1.4 on 2025-02-14 20:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_user_remove_refund_payment_and_more'),
        ('rentals', '0005_auto_20250210_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='escrow_payment',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='rental',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
        migrations.CreateModel(
            name='RentalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Upload a photo (max 5MB)', upload_to='rental_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('photo_type', models.CharField(choices=[('pre_rental', 'Pre-Rental'), ('post_rental', 'Post-Rental')], help_text='Type of photo (pre-rental or post-rental)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_photos', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Rental Photo',
                'verbose_name_plural': 'Rental Photos',
            },
        ),
        migrations.DeleteModel(
            name='EscrowPayment',
        ),
    ]
