# Generated by Django 5.1.4 on 2025-04-21 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When rental period starts')),
                ('end_time', models.DateTimeField(help_text='When rental period ends')),
                ('duration', models.PositiveIntegerField(help_text='Number of duration units')),
                ('duration_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], help_text='Unit of duration (day, week, month)', max_length=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, help_text='Total rental cost including fees', max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, editable=False, help_text='Service fee amount', max_digits=10)),
                ('purpose', models.CharField(choices=[('event', 'Event/Party'), ('personal', 'Personal Use'), ('professional', 'Professional Use'), ('other', 'Other')], help_text='Purpose of the rental', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the rental', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', help_text='Current status of the rental', max_length=50)),
                ('status_history', models.JSONField(default=list, help_text='History of status changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Upload a photo (max 5MB)', upload_to='rental_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('photo_type', models.CharField(choices=[('pre_rental', 'Pre-Rental'), ('post_rental', 'Post-Rental')], help_text='Type of photo (pre-rental or post-rental)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rental Photo',
                'verbose_name_plural': 'Rental Photos',
            },
        ),
    ]
