# Generated by Django 5.1.4 on 2025-01-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_session_key_payment_ssl_status'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('HELD', 'Payment Held in Escrow'), ('RELEASED', 'Released to Owner'), ('REFUNDED', 'Refunded to Renter'), ('DISPUTED', 'Payment Disputed')], default='HELD', max_length=20)),
                ('held_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_payment', to='rentals.rental')),
            ],
        ),
    ]
