# Generated by Django 5.1.4 on 2025-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Service fee amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total rental cost including fees', max_digits=10),
        ),
    ]
