# Generated by Django 5.1.4 on 2025-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_service_fee_alter_rental_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='purpose',
            field=models.CharField(choices=[('event', 'Event/Party'), ('personal', 'Personal Use'), ('professional', 'Professional Use'), ('other', 'Other')], default=0, help_text='Purpose of the rental', max_length=20),
            preserve_default=False,
        ),
    ]
