# Generated by Django 5.1.4 on 2025-02-09 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_escrow_payment_alter_escrowpayment_payment_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_review__c15134_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_reviewe_8bda41_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_type', 'rating'], name='reviews_rev_review__e78b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', 'reviewed_user'], name='reviews_rev_reviewe_387447_idx'),
        ),
    ]
