# Generated by Django 5.1.4 on 2025-01-14 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Security deposit required for renting', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('camera', 'Camera'), ('gimbal', 'Gimbal'), ('lighting', 'Lighting Equipment'), ('video_acc', 'Video Accessories'), ('microphone', 'Microphone'), ('studio_equip', 'Studio Equipment'), ('bicycle', 'Bicycle'), ('safety_gear', 'Helmets & Safety Gear'), ('cricket', 'Cricket Equipment'), ('football', 'Football & Soccer Equipment'), ('basketball', 'Basketball Equipment'), ('tennis', 'Tennis Equipment'), ('gym_equip', 'Gym Equipment'), ('tent', 'Tent'), ('sleeping_bag', 'Sleeping Bag'), ('camp_furniture', 'Camping Furniture'), ('hiking_gear', 'Hiking Gear'), ('camp_stove', 'Portable Stove'), ('cooler', 'Cooler'), ('speaker', 'Speaker'), ('dj_equip', 'DJ Equipment'), ('musical_inst', 'Musical Instruments'), ('karaoke', 'Karaoke Systems'), ('party_lights', 'Party Lights'), ('projector', 'Projector'), ('drone', 'Drone'), ('gaming', 'Gaming Console'), ('vr_equip', 'VR Equipment'), ('tablet', 'Tablet'), ('power_bank', 'Power Bank'), ('laptop', 'Laptop'), ('party_furniture', 'Tables & Chairs'), ('decorations', 'Decorations'), ('grill', 'Grills & BBQ Equipment'), ('bounce_house', 'Bounce House'), ('stage', 'Portable Stage'), ('power_tool', 'Power Tools'), ('hand_tool', 'Hand Tools'), ('garden_tool', 'Gardening Equipment'), ('pressure_washer', 'Pressure Washer'), ('ladder', 'Ladder'), ('paint_sprayer', 'Paint Sprayer')], help_text='Select the category that best describes your item', max_length=20, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='AvailabilityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_periods', to='advertisements.product')),
            ],
            options={
                'verbose_name': 'Availability Period',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base rental price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_unit', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], default='day', help_text='Price per duration unit', max_length=5)),
                ('minimum_rental_period', models.PositiveIntegerField(default=1, help_text='Minimum rental period in selected duration units')),
                ('maximum_rental_period', models.PositiveIntegerField(blank=True, help_text='Maximum rental period in selected duration units (leave blank for no limit)', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='advertisements.product')),
            ],
            options={
                'verbose_name': 'Pricing Option',
                'verbose_name_plural': 'Pricing Options',
            },
        ),
    ]
