# Generated by Django 5.1.4 on 2025-01-23 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_alter_availabilityperiod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_categor_22284e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_locatio_0db78d_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='product',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, editable=False, max_digits=3),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available', 'status'], name='advertiseme_categor_c0ae5d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['location', 'user'], name='advertiseme_locatio_6804af_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at', 'status'], name='advertiseme_created_2d3a18_idx'),
        ),
    ]
