# Generated by Django 5.1.4 on 2025-01-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_remove_product_advertiseme_categor_22284e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_pricing', to='advertisements.pricingoption'),
        ),
        migrations.AlterField(
            model_name='pricingoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='advertisements.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('maintenance', 'Under Maintenance'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, help_text='Enter the property title', max_length=100, verbose_name='Title'),
        ),
    ]
