# Generated by Django 5.1.4 on 2025-02-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_product_pricing_alter_pricingoption_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('camera', 'Camera'), ('gimbal', 'Gimbal'), ('lighting', 'Lighting Equipment'), ('video_acc', 'Video Accessories'), ('microphone', 'Microphone'), ('studio_equip', 'Studio Equipment'), ('bicycle', 'Bicycle'), ('safety_gear', 'Helmets & Safety Gear'), ('cricket', 'Cricket Equipment'), ('football', 'Football & Soccer Equipment'), ('basketball', 'Basketball Equipment'), ('tennis', 'Tennis Equipment'), ('gym_equip', 'Gym Equipment'), ('tent', 'Tent'), ('sleeping_bag', 'Sleeping Bag'), ('camp_furniture', 'Camping Furniture'), ('hiking_gear', 'Hiking Gear'), ('camp_stove', 'Portable Stove'), ('cooler', 'Cooler'), ('bag', 'Bag'), ('speaker', 'Speaker'), ('dj_equip', 'DJ Equipment'), ('musical_inst', 'Musical Instruments'), ('karaoke', 'Karaoke Systems'), ('party_lights', 'Party Lights'), ('projector', 'Projector'), ('drone', 'Drone'), ('gaming', 'Gaming Console'), ('vr_equip', 'VR Equipment'), ('tablet', 'Tablet'), ('power_bank', 'Power Bank'), ('laptop', 'Laptop'), ('party_furniture', 'Tables & Chairs'), ('decorations', 'Decorations'), ('grill', 'Grills & BBQ Equipment'), ('stage', 'Portable Stage'), ('power_tool', 'Power Tools'), ('hand_tool', 'Hand Tools'), ('garden_tool', 'Gardening Equipment'), ('pressure_washer', 'Pressure Washer'), ('ladder', 'Ladder'), ('paint_sprayer', 'Paint Sprayer')], db_index=True, help_text='Select the category that best describes your item', max_length=20, verbose_name='Category'),
        ),
    ]
