# Generated by Django 5.1.4 on 2025-02-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_user_remove_refund_payment_and_more'),
        ('rentals', '0006_remove_rental_escrow_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
