# Generated by Django 5.1.4 on 2025-04-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='terms_agreed',
        ),
    ]
