# Generated by Django 5.1.4 on 2025-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_customuser_terms_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_id_number',
            field=models.CharField(blank=True, help_text="User's national ID number (must be unique)", max_length=20, null=True, unique=True),
        ),
    ]
