# Generated by Django 5.1.4 on 2025-04-03 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_national_id_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text="User's average rating from reviews", max_digits=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text="User's biographical information or description", null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the user account was created'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, help_text="User's email address, used as the primary identifier for login", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token used for email verification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Indicates if the user's email has been verified"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_trusted',
            field=models.BooleanField(default=False, help_text='Indicates if the user has been verified as trustworthy by admins'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text="User's location or address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Indicates if the user has consented to receive marketing communications'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id_back',
            field=models.ImageField(blank=True, help_text="Back image of user's national ID document", null=True, upload_to='national_ids/back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id_front',
            field=models.ImageField(blank=True, help_text="Front image of user's national ID document", null=True, upload_to='national_ids/front/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's contact phone number", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed their profile with required information'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture (JPEG or PNG format)", null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the user account was last updated'),
        ),
    ]
